services:
  blinc-db:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mudcat11
      MYSQL_DATABASE: discussion_capture
      MYSQL_USER: vagrant
      MYSQL_PASSWORD: vagrant
  redis:
    image: redis
    restart: always
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    image: blinc/server:latest
    volumes:
      - ./server:/var/lib/chemistry-dashboard/server
    depends_on:
      blinc-db:
        condition: service_healthy
      redis:
        condition: service_started
  audio_processor:
    build:
      context: .
      dockerfile: docker/audio.Dockerfile
    image: blinc/audio_processor:latest
    volumes:
      - ./audio_processing:/var/lib/chemistry-dashboard/audio_processing
    depends_on:
      redis:
        condition: service_started
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    image: blinc/nginx:latest
    volumes:
      - ./frontend/build:/var/lib/chemistry-dashboard/frontend/build
      - ./UA:/var/lib/chemistry-dashboard/UA
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy/nginx-headers.conf:/etc/nginx/nginx-headers.conf
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
      - "9001:9001"
      - "9003:9003"
    depends_on:
      audio_processor:
        condition: service_healthy
      server:
        condition: service_healthy
    restart: always

