"""Add concept mapping tables

Revision ID: 09788f316dc3
Revises: 04f6d5dd536b
Create Date: 2025-10-19 20:46:14.039913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09788f316dc3'
down_revision = '04f6d5dd536b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_device_id', sa.Integer(), nullable=False),
    sa.Column('discourse_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_device_id'], ['session_device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_node',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('concept_session_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('node_type', sa.String(length=50), nullable=True),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_session_id'], ['concept_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_edge',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('concept_session_id', sa.Integer(), nullable=False),
    sa.Column('source_node_id', sa.String(length=100), nullable=False),
    sa.Column('target_node_id', sa.String(length=100), nullable=False),
    sa.Column('edge_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_session_id'], ['concept_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['concept_node.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['concept_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concept_edge')
    op.drop_table('concept_node')
    op.drop_table('concept_session')
    # ### end Alembic commands ###
