"""add llm question answer

Revision ID: 293750fc5c0e
Revises: 9d38f97ad88c
Create Date: 2026-03-24 19:06:55.440186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '293750fc5c0e'
down_revision = '9d38f97ad88c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_question_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('session_device_id', sa.Integer(), nullable=False),
    sa.Column('speaker_username', sa.String(length=64), nullable=False),
    sa.Column('default_question_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_device_id'], ['session_device.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_question_answer')
    # ### end Alembic commands ###
