"""creating survey response table

Revision ID: 42a3c6485423
Revises: 4fe6e878889f
Create Date: 2026-04-08 04:42:57.945474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42a3c6485423'
down_revision = '4fe6e878889f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sessionid', sa.Integer(), nullable=False),
    sa.Column('sessiondeviceid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_response')
    # ### end Alembic commands ###
