"""updating rater table and creating rating table

Revision ID: 4fe6e878889f
Revises: 752061083ef1
Create Date: 2026-04-06 23:33:24.208428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fe6e878889f'
down_revision = '752061083ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sessionid', sa.Integer(), nullable=False),
    sa.Column('sessiondeviceid', sa.Integer(), nullable=False),
    sa.Column('speakertag', sa.String(length=30), nullable=False),
    sa.Column('raterid', sa.String(length=30), nullable=False),
    sa.Column('evaluation_category', sa.String(length=40), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('rater', sa.Column('completed', sa.Integer(), nullable=False))
    op.add_column('rater', sa.Column('evaluation_category', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rater', 'evaluation_category')
    op.drop_column('rater', 'completed')
    op.drop_table('rating')
    # ### end Alembic commands ###
