"""Add LLMMetrics table

Revision ID: 69ee83de6b05
Revises: a4693c9702c5
Create Date: 2025-11-06 19:25:35.567559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69ee83de6b05'
down_revision = 'a4693c9702c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_device_id', sa.Integer(), nullable=False),
    sa.Column('emotional_tone_score', sa.Integer(), nullable=True),
    sa.Column('analytic_thinking_score', sa.Integer(), nullable=True),
    sa.Column('clout_score', sa.Integer(), nullable=True),
    sa.Column('authenticity_score', sa.Integer(), nullable=True),
    sa.Column('certainty_score', sa.Integer(), nullable=True),
    sa.Column('emotional_tone_explanation', sa.Text(), nullable=True),
    sa.Column('analytic_thinking_explanation', sa.Text(), nullable=True),
    sa.Column('clout_explanation', sa.Text(), nullable=True),
    sa.Column('authenticity_explanation', sa.Text(), nullable=True),
    sa.Column('certainty_explanation', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('transcript_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_device_id'], ['session_device.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_device_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_metrics')
    # ### end Alembic commands ###
