"""add llm feedback report table

Revision ID: 9d38f97ad88c
Revises: 687611104d24
Create Date: 2026-03-23 10:38:29.354657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d38f97ad88c'
down_revision = '687611104d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_feedback_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('session_device_id', sa.Integer(), nullable=False),
    sa.Column('speaker_username', sa.String(length=64), nullable=False),
    sa.Column('feedback_analysis', sa.Text(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_device_id'], ['session_device.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('llm_feedback_report')
    # ### end Alembic commands ###
