"""empty message

Revision ID: d7cd8fa96963
Revises: 
Create Date: 2019-08-07 13:54:21.692577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7cd8fa96963'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('mac_address', sa.String(length=64), nullable=True),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('is_pod', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('salt', sa.String(length=64), nullable=False),
    sa.Column('hash_pass', sa.String(length=128), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('change_password', sa.Boolean(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('passcode', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_list_item',
    sa.Column('keyword_list_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['keyword_list_id'], ['keyword_list.id'], ),
    sa.PrimaryKeyConstraint('keyword_list_id', 'keyword')
    )
    op.create_table('session_device',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('processing_key', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('button_pressed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_device_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('question', sa.Boolean(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('emotional_tone_value', sa.Integer(), nullable=True),
    sa.Column('analytic_thinking_value', sa.Integer(), nullable=True),
    sa.Column('clout_value', sa.Integer(), nullable=True),
    sa.Column('authenticity_value', sa.Integer(), nullable=True),
    sa.Column('certainty_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_device_id'], ['session_device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('keyword', sa.String(length=64), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword_usage')
    op.drop_table('transcript')
    op.drop_table('session_device')
    op.drop_table('keyword_list_item')
    op.drop_table('keyword')
    op.drop_table('session')
    op.drop_table('keyword_list')
    op.drop_table('user')
    op.drop_table('device')
    # ### end Alembic commands ###
