---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Disable nginx's default site
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Copy nginx headers and config
  template:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
  with_items:
    - {src: templates/nginx-headers.conf.j2, dest: /etc/nginx/nginx-headers.conf}
    - {src: templates/nginx.conf.j2, dest: /etc/nginx/nginx.conf}