---

# - name: Multi sample
#   apt:
#       name: "{{ item }}"
#       update_cache: true
#       state: present
#   with_items:
#       - 'python3-pip'
#       - 'python-setuptools'
#       - 'ansible'
#       - 'libmysqlclient-dev'
#       - 'mysql-client-core-5.7'

- name: Install python3 via APT
  apt:
    name: python3
    state: present

- name: Install python3-dev via APT
  apt:
    name: python3-dev
    state: present

- name: Install python3-venv via APT
  apt:
    name: python3-venv
    state: present

- name: Install pip3 via APT
  apt:
    name: python3-pip
    state: present

- name: Install mysql tools required by python mysql tools
  apt:
    name: 
      - libmysqlclient-dev
      - mysql-client-core-5.7
    state: present

- name: Install virtualenv, boto3, passlib global packages
  pip:
    name:
        - virtualenv
        - boto3
        - passlib
    executable: pip3
