"""empty message

Revision ID: 04f6d5dd536b
Revises: 35f6e8996162
Create Date: 2025-05-14 16:04:10.597551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f6d5dd536b'
down_revision = '35f6e8996162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('speaker_ibfk_1', 'speaker', type_='foreignkey')
    op.create_foreign_key(None, 'speaker', 'session_device', ['session_device_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('speaker_transcript_metrics_ibfk_2', 'speaker_transcript_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'speaker_transcript_metrics', 'transcript', ['transcript_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'speaker_transcript_metrics', type_='foreignkey')
    op.create_foreign_key('speaker_transcript_metrics_ibfk_2', 'speaker_transcript_metrics', 'transcript', ['transcript_id'], ['id'])
    op.drop_constraint(None, 'speaker', type_='foreignkey')
    op.create_foreign_key('speaker_ibfk_1', 'speaker', 'session_device', ['session_device_id'], ['id'])
    # ### end Alembic commands ###
