"""Add agent_version to agent_conversation

Revision ID: 1121997bdbf6
Revises: 4a252cd0ce84
Create Date: 2026-01-11 20:06:31.184640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1121997bdbf6'
down_revision = '4a252cd0ce84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add agent_version column with default 'v3' for existing rows
    op.add_column('agent_conversation', sa.Column('agent_version', sa.String(length=10), nullable=False, server_default='v3'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_conversation', 'agent_version')
    # ### end Alembic commands ###
