"""adding session_synthesis_report table

Revision ID: 17a31a91c8c7
Revises: 870b15146a16
Create Date: 2026-04-03 15:00:05.779597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17a31a91c8c7'
down_revision = '870b15146a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_synthesized_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('session_device_id', sa.Integer(), nullable=False),
    sa.Column('synthesized_feedback', mysql.LONGTEXT(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_device_id'], ['session_device.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_synthesized_report')
    # ### end Alembic commands ###
