"""empty message

Revision ID: 1a98748010e7
Revises: c663e443ee71
Create Date: 2023-09-20 10:39:54.986092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a98748010e7'
down_revision = 'c663e443ee71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id_idx', table_name='topic_model')
    op.create_foreign_key(None, 'topic_model', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic_model', type_='foreignkey')
    op.create_index('user_id_idx', 'topic_model', ['owner_id'], unique=False)
    # ### end Alembic commands ###
