"""add speaker_transcript_metrics table

Revision ID: 35f6e8996162
Revises: b3d7df066443
Create Date: 2025-03-05 13:53:11.841668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f6e8996162'
down_revision = 'b3d7df066443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaker_transcript_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('participation_score', sa.Float(), nullable=True),
    sa.Column('internal_cohesion', sa.Float(), nullable=True),
    sa.Column('responsivity', sa.Float(), nullable=True),
    sa.Column('social_impact', sa.Float(), nullable=True),
    sa.Column('newness', sa.Float(), nullable=True),
    sa.Column('communication_density', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker.id'], ),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speaker_transcript_metrics')
    # ### end Alembic commands ###
