"""user_system_interaction table

Revision ID: 483e8c8124c0
Revises: 42a3c6485423
Create Date: 2026-05-11 01:15:24.134741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '483e8c8124c0'
down_revision = '42a3c6485423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_system_interaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sessionid', sa.Integer(), nullable=False),
    sa.Column('sessiondeviceid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_system_interaction')
    # ### end Alembic commands ###
