"""empty message

Revision ID: 487b863fdab2
Revises: 5d17848fa1f7
Create Date: 2023-11-09 12:24:06.801931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487b863fdab2'
down_revision = '5d17848fa1f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcript', sa.Column('topic_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcript', 'topic_id')
    # ### end Alembic commands ###
