"""Add discussion_pulse table

Revision ID: 4a252cd0ce84
Revises: a13d95eb7da7
Create Date: 2025-11-27 20:03:52.088388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a252cd0ce84'
down_revision = 'a13d95eb7da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion_pulse',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_device_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('speaker_count', sa.Integer(), nullable=True),
    sa.Column('dominant_speaker_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('transcript_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dominant_speaker_id'], ['speaker.id'], ),
    sa.ForeignKeyConstraint(['session_device_id'], ['session_device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('concept_session', sa.Column('generated_at', sa.DateTime(), nullable=True))
    op.add_column('concept_session', sa.Column('generation_error', sa.Text(), nullable=True))
    op.add_column('concept_session', sa.Column('generation_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concept_session', 'generation_status')
    op.drop_column('concept_session', 'generation_error')
    op.drop_column('concept_session', 'generated_at')
    op.drop_table('discussion_pulse')
    # ### end Alembic commands ###
