"""updating foriegn key relationships for tables

Revision ID: 55b46b0c86b7
Revises: 17a31a91c8c7
Create Date: 2026-04-04 19:01:40.361462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55b46b0c86b7'
down_revision = '17a31a91c8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('llm_feedback_report_ibfk_1', 'llm_feedback_report', type_='foreignkey')
    op.create_foreign_key(None, 'llm_feedback_report', 'session_device', ['session_device_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('llm_question_answer_ibfk_1', 'llm_question_answer', type_='foreignkey')
    op.create_foreign_key(None, 'llm_question_answer', 'session_device', ['session_device_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('session_synthesized_report_ibfk_2', 'session_synthesized_report', type_='foreignkey')
    op.create_foreign_key(None, 'session_synthesized_report', 'session', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('transcript_ibfk_1', 'transcript', type_='foreignkey')
    op.create_foreign_key(None, 'transcript', 'session_device', ['session_device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transcript', type_='foreignkey')
    op.create_foreign_key('transcript_ibfk_1', 'transcript', 'session_device', ['session_device_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'session_synthesized_report', type_='foreignkey')
    op.create_foreign_key('session_synthesized_report_ibfk_2', 'session_synthesized_report', 'session', ['session_id'], ['id'])
    op.drop_constraint(None, 'llm_question_answer', type_='foreignkey')
    op.create_foreign_key('llm_question_answer_ibfk_1', 'llm_question_answer', 'session_device', ['session_device_id'], ['id'])
    op.drop_constraint(None, 'llm_feedback_report', type_='foreignkey')
    op.create_foreign_key('llm_feedback_report_ibfk_1', 'llm_feedback_report', 'session_device', ['session_device_id'], ['id'])
    
    # ### end Alembic commands ###
