"""Add new table or update definition

Revision ID: 727233320931
Revises: 04f6d5dd536b
Create Date: 2025-06-26 02:26:56.465718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727233320931'
down_revision = '04f6d5dd536b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=10), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
