"""updating foriegn key relationships for tables 22

Revision ID: 752061083ef1
Revises: 55b46b0c86b7
Create Date: 2026-04-04 19:18:34.269868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '752061083ef1'
down_revision = '55b46b0c86b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('session_synthesized_report_ibfk_2', 'session_synthesized_report', type_='foreignkey')
    op.drop_constraint('session_synthesized_report_ibfk_1', 'session_synthesized_report', type_='foreignkey')
    op.create_foreign_key(None, 'session_synthesized_report', 'session_device', ['session_device_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'session_synthesized_report', 'session', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_synthesized_report', type_='foreignkey')
    op.drop_constraint(None, 'session_synthesized_report', type_='foreignkey')
    op.create_foreign_key('session_synthesized_report_ibfk_1', 'session_synthesized_report', 'session_device', ['session_device_id'], ['id'])
    op.create_foreign_key('session_synthesized_report_ibfk_2', 'session_synthesized_report', 'session', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
