"""add SpeakerVideoMetrics table

Revision ID: 7da13891981c
Revises: 727233320931
Create Date: 2025-10-11 04:58:55.004134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da13891981c'
down_revision = '727233320931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaker_video_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_device_id', sa.Integer(), nullable=False),
    sa.Column('student_username', sa.String(length=20), nullable=False),
    sa.Column('time_stamp', sa.Integer(), nullable=False),
    sa.Column('facial_emotion', sa.String(length=64), nullable=False),
    sa.Column('attention_level', sa.Integer(), nullable=True),
    sa.Column('object_on_focus', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['session_device_id'], ['session_device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('keyword', sa.String(length=64), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword_usage')
    op.drop_table('speaker_video_metrics')
    # ### end Alembic commands ###
