"""add biometric_captured to student

Revision ID: 85aa1f4d787b
Revises: 7da13891981c
Create Date: 2025-10-22 04:21:51.631981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85aa1f4d787b'
down_revision = '7da13891981c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('biometric_captured', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'biometric_captured')
    # ### end Alembic commands ###
