"""add raters table

Revision ID: 870b15146a16
Revises: 293750fc5c0e
Create Date: 2026-04-01 00:47:53.411760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '870b15146a16'
down_revision = '293750fc5c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rater',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sessionid', sa.Integer(), nullable=False),
    sa.Column('sessiondeviceid', sa.Integer(), nullable=False),
    sa.Column('speakerid', sa.Integer(), nullable=False),
    sa.Column('speakertag', sa.String(length=30), nullable=False),
    sa.Column('raterid', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rater')
    # ### end Alembic commands ###
