"""Add 7Cs analysis tables

Revision ID: a13d95eb7da7
Revises: a41421e7eae0
Create Date: 2025-11-20 17:18:40.137540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a13d95eb7da7'
down_revision = 'a41421e7eae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seven_cs_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_device_id', sa.Integer(), nullable=False),
    sa.Column('analysis_summary', sa.JSON(), nullable=True),
    sa.Column('analysis_status', sa.String(length=20), nullable=True),
    sa.Column('total_segments_analyzed', sa.Integer(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('llm_model_used', sa.String(length=50), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_device_id'], ['session_device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seven_cs_coded_segment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text_snippet', sa.Text(), nullable=False),
    sa.Column('speaker_tag', sa.String(length=64), nullable=True),
    sa.Column('coding_reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['seven_cs_analysis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_dimension', 'seven_cs_coded_segment', ['analysis_id', 'dimension'], unique=False)
    op.create_index('idx_analysis_time', 'seven_cs_coded_segment', ['analysis_id', 'start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_analysis_time', table_name='seven_cs_coded_segment')
    op.drop_index('idx_analysis_dimension', table_name='seven_cs_coded_segment')
    op.drop_table('seven_cs_coded_segment')
    op.drop_table('seven_cs_analysis')
    # ### end Alembic commands ###
