"""adding speakers table

Revision ID: a35791f5108b
Revises: 487b863fdab2
Create Date: 2024-09-06 11:49:52.991521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35791f5108b'
down_revision = '487b863fdab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_device_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['session_device_id'], ['session_device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speaker')
    # ### end Alembic commands ###
