"""Add concept clustering tables

Revision ID: a4693c9702c5
Revises: f7e628296088
Create Date: 2025-10-27 20:06:14.994399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4693c9702c5'
down_revision = 'f7e628296088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_cluster',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concept_session_id', sa.Integer(), nullable=False),
    sa.Column('cluster_name', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('centroid_node_id', sa.String(length=100), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=True),
    sa.Column('cluster_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['centroid_node_id'], ['concept_node.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['concept_session_id'], ['concept_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cluster_node_mapping',
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['concept_cluster.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['concept_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cluster_id', 'node_id')
    )
    #op.drop_table('speaker_video_metrics')
    #op.drop_table('student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('student',
    #sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    #sa.Column('lastname', mysql.VARCHAR(length=50), nullable=False),
    #sa.Column('firstname', mysql.VARCHAR(length=50), nullable=False),
    #sa.Column('username', mysql.VARCHAR(length=10), nullable=False),
    #sa.Column('creation_date', mysql.DATETIME(), nullable=False),
    #sa.Column('biometric_captured', mysql.VARCHAR(length=3), nullable=True),
    #sa.PrimaryKeyConstraint('id'),
    #mysql_collate='utf8mb4_0900_ai_ci',
    #mysql_default_charset='utf8mb4',
    #mysql_engine='InnoDB'
    #)
    #op.create_table('speaker_video_metrics',
    #sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    #sa.Column('session_device_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    #sa.Column('student_username', mysql.VARCHAR(length=20), nullable=False),
    #sa.Column('time_stamp', mysql.INTEGER(), autoincrement=False, nullable=False),
    #sa.Column('facial_emotion', mysql.VARCHAR(length=64), nullable=False),
    #sa.Column('attention_level', mysql.INTEGER(), autoincrement=False, nullable=True),
    #sa.Column('object_on_focus', mysql.VARCHAR(length=128), nullable=True),
    #sa.ForeignKeyConstraint(['session_device_id'], ['session_device.id'], name='speaker_video_metrics_ibfk_1'),
    #sa.PrimaryKeyConstraint('id'),
    #mysql_collate='utf8mb4_0900_ai_ci',
    #mysql_default_charset='utf8mb4',
    #mysql_engine='InnoDB'
    #)
    op.drop_table('cluster_node_mapping')
    op.drop_table('concept_cluster')
    # ### end Alembic commands ###
