"""add speaker_id to transcript

Revision ID: b3d7df066443
Revises: a35791f5108b
Create Date: 2024-10-16 22:02:37.575770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d7df066443'
down_revision = 'a35791f5108b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcript', sa.Column('speaker_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcript', 'speaker_id')
    # ### end Alembic commands ###
