"""empty message

Revision ID: c663e443ee71
Revises: 2f696fa6cac7
Create Date: 2019-11-22 18:14:27.328960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c663e443ee71'
down_revision = '2f696fa6cac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcript', sa.Column('speaker_tag', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcript', 'speaker_tag')
    # ### end Alembic commands ###
