"""empty message

Revision ID: f02d9c90dca8
Revises: a52190d958cf
Create Date: 2019-09-04 15:20:45.679733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02d9c90dca8'
down_revision = 'a52190d958cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent'], ['folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('session', sa.Column('folder', sa.Integer(), nullable=True))
    op.create_foreign_key('session_folder', 'session', 'folder', ['folder'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('session_folder', 'session', type_='foreignkey')
    op.drop_column('session', 'folder')
    op.drop_table('folder')
    # ### end Alembic commands ###
