"""Fix cascade delete for concepts

Revision ID: f7e628296088
Revises: 09788f316dc3
Create Date: 2025-10-21 05:03:44.121460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e628296088'
down_revision = '09788f316dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('concept_edge_ibfk_3', 'concept_edge', type_='foreignkey')
    op.drop_constraint('concept_edge_ibfk_2', 'concept_edge', type_='foreignkey')
    op.create_foreign_key(None, 'concept_edge', 'concept_node', ['target_node_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'concept_edge', 'concept_node', ['source_node_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('concept_node_ibfk_2', 'concept_node', type_='foreignkey')
    op.create_foreign_key(None, 'concept_node', 'speaker', ['speaker_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('concept_session_ibfk_1', 'concept_session', type_='foreignkey')
    op.create_foreign_key(None, 'concept_session', 'session_device', ['session_device_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'concept_session', type_='foreignkey')
    op.create_foreign_key('concept_session_ibfk_1', 'concept_session', 'session_device', ['session_device_id'], ['id'])
    op.drop_constraint(None, 'concept_node', type_='foreignkey')
    op.create_foreign_key('concept_node_ibfk_2', 'concept_node', 'speaker', ['speaker_id'], ['id'])
    op.drop_constraint(None, 'concept_edge', type_='foreignkey')
    op.drop_constraint(None, 'concept_edge', type_='foreignkey')
    op.create_foreign_key('concept_edge_ibfk_2', 'concept_edge', 'concept_node', ['source_node_id'], ['id'])
    op.create_foreign_key('concept_edge_ibfk_3', 'concept_edge', 'concept_node', ['target_node_id'], ['id'])
    # ### end Alembic commands ###
